### ISSUE TITLE
How can I print/view this union/struc?

### ISSUE THREAD

**Issue by mprowe** [codebrainz/ina260#1]
If I consider this section you code:
```
  // create an instance of the register structure. note the ={0} used
  // to zero-initialize the instance. You could also use memset() or
  // manually initialize all of the fields to zero. All of the fields
  // are written to the config. register so you want to make sure you
  // know what they're all set to.
  INA260::ConfigurationRegister configReg = {0, 0, 0, 0, 0};
  
  configReg.mode   = INA260::MODE_ISH_VBUS_CONTINUOUS;  // continuously sample voltage and current (this is default)
  configReg.ishct  = INA260::ISHCT_1_1MS;               // allow 2.116ms also for the ADC sampling of the current
  configReg.vbusct = INA260::VBUSCT_1_1MS;              // allow 2.116ms for the ADC sampling of the bus voltage
  configReg.avg    = INA260::AVG_16;                    // average 64 samples for each reading
  
  ina260.writeConfigurationRegister(configReg);         //Write the configuration register to the INA260 over I2C

```
How can I print _**configReg**_ to see the bit pattern? 

Regards, M.

**Comment by codebrainz** [comment]
Not sure if there's anything Arduino specific, but you might find some of the ideas here useful:

* https://stackoverflow.com/q/111928
* https://stackoverflow.com/q/699968

You can do it on the `configReg.rawValue` 16-bit member of the union, or on the individual members of the anonymous struct inside the union separately depending on what you want.

**Comment by mprowe** [comment]
Thank you Matthew,
Those links are very helpful. 
Since posting my original question, the question(for me) has broadened out to the wider issue of:
How do I iterate over ANY struct? I was hoping for something like the forEach() method in Java.
But it seems that is not possible in Arduino/C++.
Anyway, thank you for your help - And your INA260 library - it is very useful.
Regards, M.
